# Ansible configuration
ansible_python_interpreter: /usr/bin/python3

# Services ports
adguard_home_web_port: 3000
dashy_web_port: 9080
file_browser_web_port: 4000
glances_web_port: 61208
metube_web_port: 8081
navidrome_web_port: 9700
olivetin_port: 1337 # This port is fixed/non-dynamic
pihole_web_port: 8070
portainer_web_port: 9443
stirling_pdf_web_port: 7000
uptime_kuma_web_port: 3001
vaultwarden_web_port: 8222
vikunja_web_port: 3456

# Configs passwords
nas_password: "{{ vault_nas_password }}"
cloudflare_token: "{{ vault_cloudflare_token }}"
duckdns_token: "{{ vault_duckdns_token }}"
dns_email: "{{ vault_dns_email }}"

# Services passwords
navidrome_lastfm_api_key: "{{ vault_lastfm_api_key }}"
navidrome_lastfm_shared_secret: "{{ vault_lastfm_shared_secret }}"
olivetin_user_password: "{{ vault_olivetin_user_password }}" 
vaultwarden_admin_token: "{{ vault_vaultwarden_admin_token }}"

# Hosts IPs
dns_host_ip: "192.168.0.88"
