# Ansible configuration
ansible_python_interpreter: /usr/bin/python3

# Services ports
adguard_home_web_port: 3000
dashy_web_port: 9080
file_browser_web_port: 4000
glances_web_port: 61208
metube_web_port: 8081
navidrome_web_port: 9700
olivetin_port: 1337 # This port is fixed/non-dynamic
pihole_web_port: 8070
portainer_web_port: 9443
stirling_pdf_web_port: 7000
uptime_kuma_web_port: 3001
vaultwarden_web_port: 8222
vikunja_web_port: 3456

# Host IPs
raspberry_host_ip: "192.168.0.88"
services_host_ip: "192.168.0.200"
nas_host_ip: "192.168.0.201"
