xcaddy_version: "0.4.5"
xcaddy_download_url: "https://github.com/caddyserver/xcaddy/releases/download/v{{ xcaddy_version }}/xcaddy_{{ xcaddy_version }}_linux_{{ system_arch }}.tar.gz"

caddy_user: caddy
caddy_group: caddy
