- name: Debug system architecture
  ansible.builtin.debug:
    msg: "System architecture: {{ system_arch }}"

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_url }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }}] {{ docker_repo_url }} {{ docker_debian_version }} stable"

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: latest

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reconnect to refresh user groups
  ansible.builtin.meta: reset_connection
