- name: Create APT keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_gpg_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Convert Docker GPG key to keyring format
  ansible.builtin.command:
    cmd: >
      gpg --batch --yes --dearmor
      --output /etc/apt/keyrings/docker.gpg
      /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.gpg

- name: Ensure Docker GPG key permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'


- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ system_arch }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      {{ docker_repo_url }}
      {{ docker_debian_version }} stable
    state: present
    filename: docker

- name: Pin Docker packages to specific versions
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/docker
    owner: root
    group: root
    mode: '0644'
    content: |
      Package: docker-ce
      Pin: version 5:29.2.0-1~debian.12~bookworm
      Pin-Priority: {{ docker_pin_priority }}

      Package: docker-ce-cli
      Pin: version 5:29.2.0-1~debian.12~bookworm
      Pin-Priority: {{ docker_pin_priority }}

      Package: containerd.io
      Pin: version 2.2.1-1~debian.12~bookworm
      Pin-Priority: {{ docker_pin_priority }}

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reconnect to refresh user groups
  ansible.builtin.meta: reset_connection
