storage_uuid: "257d85bc-003d-46df-8405-0e6135a0c94f"
nas_root: /mnt/storage

nas_admin_user: glomyer
nas_admin_group: nas_admins
nas_storage_share: storage

# Domain groups
nas_domain_groups:
  - media_music_ro
  - media_videos_ro

nas_services:
  - name: navidrome
    password: "{{ vault_nas_navidrome_password }}"
    share: music
    domain_group: media_music_ro

  - name: jellyfin
    password: "{{ vault_nas_jellyfin_password }}"
    share: videos
    domain_group: media_videos_ro

nas_shares:
  - name: music
    path: "{{ nas_root }}/music"
    domain_group: media_music_ro
    read_only: true

  - name: videos
    path: "{{ nas_root }}/videos"
    domain_group: media_videos_ro
    read_only: true
