- name: Configure NAS
  hosts: [NasHost]
  become: true
  roles:
    - role: configure_nas
      tags: configure_nas

- name: Configure SMB Share mounts
  hosts: [ServicesHost]
  become: true
  roles:
    - role: smb_mounts
      tags: smb_mounts
