- name: Set up containerized services
  hosts: raspberry
  roles:
    - role: adguard_home
      tags: adguard_home

    - role: dashy
      tags: dashy

    - role: file_browser
      tags: file_browser

    - role: glances
      tags: glances

    - role: metube
      tags: metube

    - role: navidrome
      tags: navidrome

    # - role: pihole
    #   tags: pihole

    - role: portainer
      tags: portainer

    - role: stirling_pdf
      tags: stirling_pdf

    - role: uptime_kuma
      tags: uptime_kuma

    - role: vaultwarden
      tags: vaultwarden

    - role: vikunja
      tags: vikunja
