- name: Set up containerized services
  hosts: [raspberry]
  roles:
    - role: containers/adguard_home
      tags: adguard_home

    - role: containers/dashy
      tags: dashy

    - role: containers/file_browser
      tags: file_browser

    - role: containers/glances
      tags: glances

    - role: containers/metube
      tags: metube

    - role: containers/navidrome
      tags: navidrome

    # - role: containers/pihole
    #   tags: pihole

    - role: containers/portainer
      tags: portainer

    - role: containers/stirling_pdf
      tags: stirling_pdf

    - role: containers/uptime_kuma
      tags: uptime_kuma

    - role: containers/vaultwarden
      tags: vaultwarden

    - role: containers/vikunja
      tags: vikunja
